### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by nignatiadis** [nignatiadis/RegressionDiscontinuity.jl#20]
# Roadmap 

## Approaches to inference in sharp RDs

- [ ] Robust bias-corrected inference in rdrobust package

- [ ] [Noise Induced Randomization](https://arxiv.org/pdf/2004.09458.pdf)  (todo: document)

- [ ] Inference accounting for worst-case smoothness
  - [ ] OptRDD (Imbens and Wager, 2019)
  - [ ] [RDHonest](https://github.com/kolesarm/RDHonest)
  - [ ] Bounded misspecification inference for discrete RVs (https://www.aeaweb.org/articles?id=10.1257/aer.20160945)

- [ ] Local randomization [rdlocrand](https://rdpackages.github.io/rdlocrand)

- [ ] Naive local polynomial regression (not really inference..)
  - [ ] p = 1 (local linear)
  - [ ] p > 1 

### Bandwidths 

- [ ] Imbens-Kalyanaraman bandwidth
   - [ ] p = 1 (local linear)
   - [ ] p > 1 
- [ ] RDrobust second generation bandwidths for point and bias estimation 

### Curvature bounds 

- [ ] OptRDD heuristic
- [ ] RDHonest heuristic
- [ ] Noise induced randomization bounds

## Manipulation

- [ ] McCrary density test
- [ ] Density tests in the [rddensity](https://rdpackages.github.io/rddensity) package.
- [ ] Partial identification results under manipulation

## Plotting

- [ ] Histogram of running variable
- [ ] Basic binscatter
- [ ] RD plots and binsize selection as in (https://rdpackages.github.io/references/Calonico-Cattaneo-Titiunik_2015_JASA.pdf)

## Empirical sanity checks 

- [ ] Sensitivity analysis 
- [ ] Placebo tests 

## Longer term extensions
- [ ] Fuzzy designs 
- [ ] Multidimensional running variable 
- [ ] RD with covariates
